### ISSUE TITLE
Uncaught TypeError: Cannot read property 'statusCode' of undefined

### ISSUE THREAD

**Issue by standjbg** [ceceppa/codepress-atom#1]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.40.0 x64
**Electron**: 3.1.10
**OS**: Microsoft Windows 10 Pro
**Thrown From**: [CodePress](https://github.com/ceceppa/codepress-atom) package 0.3.0

### Stack Trace

Uncaught TypeError: Cannot read property 'statusCode' of undefined

```
At C:\Users\Stan - GazeUP\.atom\packages\CodePress\lib\codepress-request.coffee:72

TypeError: Cannot read property 'statusCode' of undefined
    at Request._callback (/packages/CodePress/lib/codepress-request.coffee:72:23)
    at self.callback (/packages/atom-beautify/node_modules/request/request.js:185:22)
    at Request.emit (events.js:182:13)
    at Request.onRequestError (/packages/atom-beautify/node_modules/request/request.js:881:8)
    at ClientRequest.emit (events.js:182:13)
    at Socket.socketErrorListener (_http_client.js:382:9)
    at Socket.emit (events.js:182:13)
    at emitErrorNT (internal/streams/destroy.js:82:8)
    at emitErrorAndCloseNT (internal/streams/destroy.js:50:3)
    at process._tickCallback (internal/process/next_tick.js:63:19)
```

### Commands

```
     -2:53.4.0 core:select-all (input.hidden-input)
  5x -2:47.4.0 intentions:highlight (input.hidden-input)
     -2:46.7.0 core:paste (input.hidden-input)
  9x -2:44.3.0 intentions:highlight (input.hidden-input)
     -2:43.5.0 core:save (input.hidden-input)
     -2:30.1.0 atom-beautify:beautify-editor (div.line)
     -2:28.2.0 intentions:highlight (input.hidden-input)
     -2:27.8.0 core:save (input.hidden-input)
 22x -2:05.5.0 intentions:highlight (input.hidden-input)
 49x -2:04.3.0 core:undo (input.hidden-input)
     -1:49.4.0 intentions:highlight (input.hidden-input)
     -1:49 core:save (input.hidden-input)
     -0:44.6.0 intentions:highlight (input.hidden-input)
     -0:44.6.0 core:select-all (input.hidden-input)
     -0:40.3.0 spell-check:correct-misspelling (div.line)
     -0:31.4.0 codepress-atom:toggle (div.line)
```

### Non-Core Packages

```
advanced-open-file 0.16.8 
ask-stack 2.2.0 
atom-beautify 0.33.4 
atom-clock 0.1.17 
atom-clock-alarm 3.5.0 
atom-dark-sexy-dim-theme-syntax 0.7.2 
atom-dark-sexy-dim-ui-theme 0.1.4 
atom-live-server 2.3.0 
atom-material-syntax 1.0.8 
atom-material-ui 2.1.3 
atom-select-npm-install 1.0.2 
atom-ternjs 0.20.0 
autoclose-html 0.23.0 
base16-material-syntax 1.11.0 
bright-yellow-syntax 0.3.0 
busy-signal 2.0.1 
chester-atom-syntax 0.3.2 
CodePress 0.3.0 
color-picker 2.3.0 
csslint 1.2.0 
dark-one-dark-syntax 2.3.0 
dotinstall-pane 0.2.0 
emmet 2.4.3 
expose 0.15.0 
flat-yellow-ui 0.1.0 
framer-ui 2.0.0 
full-yellow-syntax 0.1.0 
git-blame 1.8.0 
highlight-selected 0.17.0 
hyperclick 0.1.5 
intentions 1.1.5 
ionide-fake 1.2.2 
ionide-fsharp 1.9.3 
ionide-fsi 2.1.3 
ionide-installer 1.4.0 
ionide-paket 2.2.6 
ionide-webview 1.0.3 
kde-breeze-dark-ui 1.0.1 
language-ejs 0.4.0 
language-liquid 0.7.0 
less-than-slash 0.19.0 
linter 2.3.1 
linter-jshint 3.1.18 
linter-ui-default 1.8.1 
material-dark-soda-syntax 1.0.0 
material-monokai-syntax 1.0.1 
minimap 4.29.9 
npm-install 4.0.4 
nue-syntax 0.0.2 
numix-ui 0.2.3 
one-dark-material-syntax 1.0.3 
pigments 0.40.2 
project-manager 3.3.8 
teletype 0.13.4 
ticker-clock 0.1.0 
todo-show 2.3.2 
turbo-javascript 1.4.0 
win10-ui 0.4.10 
```

**Comment by ceceppa** [comment]
Hi,
sorry for the late reply.
Unfortunately, the original project is abandoned.
